In [89]:
import numpy as np
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

In [90]:
# https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset
credits=pd.read_csv('credits.csv')
credits

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [91]:
metadata=pd.read_csv('movies_metadata.csv', low_memory=False)
metadata

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [92]:
metadata['release_date'] = pd.to_datetime(metadata['release_date'], errors='coerce')
metadata['year'] = metadata['release_date'].dt.year

metadata['year'].value_counts().sort_index()

year
1874.0       1
1878.0       1
1883.0       1
1887.0       1
1888.0       2
          ...
2015.0    1905
2016.0    1604
2017.0     532
2018.0       5
2020.0       1
Name: count, Length: 135, dtype: int64

In [93]:
metadata = metadata.loc[metadata.year <= 2017,['genres','id','title','year']]

In [94]:
metadata['id'] = metadata['id'].astype(int)

In [95]:
df = pd.merge(metadata, credits, on='id')
df

,genres,id,title,year,cast,crew
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,1995.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,1995.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,1995.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,Waiting to Exhale,1995.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"[{'id': 35, 'name': 'Comedy'}]",11862,Father of the Bride Part II,1995.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...
45440,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,Robin Hood,1991.0,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de..."
45441,"[{'id': 18, 'name': 'Drama'}]",111109,Century of Birthing,2011.0,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de..."
45442,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,Betrayal,2003.0,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de..."
45443,[],227506,Satan Triumphant,1917.0,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de..."
45444,[],461257,Queerama,2017.0,[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

In [96]:
import ast

def refine(x):
    L = []
    x=ast.literal_eval(x)
    for i in x:
        if i['name']=='Science Fiction':
            L.append('Sci-Fi')
        else:
            L.append(i['name'])

    return L

df['genres'] = df['genres'].progress_apply(refine)

100%|██████████| 45445/45445 [00:01<00:00, 33334.54it/s]

In [97]:
def refine(x):
    L = []
    for i in ast.literal_eval(x):
        L.append(i['name'])
        if(len(L)>=3):
            break

    return L

df['cast'] = df['cast'].progress_apply(refine)

100%|██████████| 45445/45445 [00:24<00:00, 1856.61it/s]

In [98]:
def refine(x):
    L = []
    for i in ast.literal_eval(x):
        if i['job']=='Director':
            L.append(i['name'])
            break

    return L

df['crew'] = df['crew'].progress_apply(refine)

100%|██████████| 45445/45445 [00:18<00:00, 2495.55it/s]

In [99]:
df = df[~df.isin([[]]).any(axis=1)]
df

,genres,id,title,year,cast,crew
0,"[Animation, Comedy, Family]",862,Toy Story,1995.0,"[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter]
1,"[Adventure, Fantasy, Family]",8844,Jumanji,1995.0,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston]
2,"[Romance, Comedy]",15602,Grumpier Old Men,1995.0,"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch]
3,"[Comedy, Drama, Romance]",31357,Waiting to Exhale,1995.0,"[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker]
4,[Comedy],11862,Father of the Bride Part II,1995.0,"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer]
...,...,...,...,...,...,...
45438,[Horror],289923,The Burkittsville 7,2000.0,"[Monty Bane, Lucy Butler, David Grammer]",[Ben Rock]
45439,[Sci-Fi],222848,Caged Heat 3000,1995.0,"[Lisa Boyle, Kena Land, Zaneta Polard]",[Aaron Osborne]
45440,"[Drama, Action, Romance]",30840,Robin Hood,1991.0,"[Patrick Bergin, Uma Thurman, David Morrissey]",[John Irvin]
45441,[Drama],111109,Century of Birthing,2011.0,"[Angel Aquino, Perry Dizon, Hazel Orencio]",[Lav Diaz]
45442,"[Action, Drama, Thriller]",67758,Betrayal,2003.0,"[Erika Eleniak, Adam Baldwin, Julie du Page]",[Mark L. Lester]

In [105]:
df.loc[:,'title'] = df['title'].str.lower()
df.loc[:,'member'] = df.loc[:,'cast']+df.loc[:,'crew']
df=df.drop_duplicates(subset ="title", keep = 'last')

In [108]:
df.loc[:,'Title']=df['title']
df.loc[:,'director']=df['crew']
df.loc[:,'actors']=df['cast']
df=df[['Title','genres','director','actors']]

In [109]:
df.to_csv('processed_tmdb.csv',index=False)